particle minecraft:basic_flame_particle ~-2.5 ~2 ~-1.5
particle minecraft:basic_flame_particle ~-2.5 ~2 ~-1.0
particle minecraft:basic_flame_particle ~-2.5 ~2 ~-0.5
particle minecraft:basic_flame_particle ~-2.5 ~2 ~0.0
particle minecraft:basic_flame_particle ~-2.5 ~2 ~0.5
particle minecraft:basic_flame_particle ~-2.5 ~2 ~1.0
particle minecraft:basic_flame_particle ~-2.5 ~2 ~1.5
particle minecraft:basic_flame_particle ~-2.0 ~2 ~-2.0
particle minecraft:basic_flame_particle ~-2.0 ~2 ~-1.5
particle minecraft:basic_flame_particle ~-2.0 ~2 ~1.5
particle minecraft:basic_flame_particle ~-2.0 ~2 ~2.0
particle minecraft:basic_flame_particle ~-1.5 ~2 ~-2.5
particle minecraft:basic_flame_particle ~-1.5 ~2 ~-2.0
particle minecraft:basic_flame_particle ~-1.5 ~2 ~2.0
particle minecraft:basic_flame_particle ~-1.5 ~2 ~2.5
particle minecraft:basic_flame_particle ~-1.0 ~2 ~-2.5
particle minecraft:basic_flame_particle ~-1.0 ~2 ~2.5
particle minecraft:basic_flame_particle ~-0.5 ~2 ~-2.5
particle minecraft:basic_flame_particle ~-0.5 ~2 ~2.5
particle minecraft:basic_flame_particle ~0.0 ~2 ~-2.5
particle minecraft:basic_flame_particle ~0.0 ~2 ~2.5
particle minecraft:basic_flame_particle ~0.5 ~2 ~-2.5
particle minecraft:basic_flame_particle ~0.5 ~2 ~2.5
particle minecraft:basic_flame_particle ~1.0 ~2 ~-2.5
particle minecraft:basic_flame_particle ~1.0 ~2 ~2.5
particle minecraft:basic_flame_particle ~1.5 ~2 ~-2.5
particle minecraft:basic_flame_particle ~1.5 ~2 ~-2.0
particle minecraft:basic_flame_particle ~1.5 ~2 ~2.0
particle minecraft:basic_flame_particle ~1.5 ~2 ~2.5
particle minecraft:basic_flame_particle ~2.0 ~2 ~-2.0
particle minecraft:basic_flame_particle ~2.0 ~2 ~-1.5
particle minecraft:basic_flame_particle ~2.0 ~2 ~1.5
particle minecraft:basic_flame_particle ~2.0 ~2 ~2.0
particle minecraft:basic_flame_particle ~2.5 ~2 ~-1.5
particle minecraft:basic_flame_particle ~2.5 ~2 ~-1.0
particle minecraft:basic_flame_particle ~2.5 ~2 ~-0.5
particle minecraft:basic_flame_particle ~2.5 ~2 ~0.0
particle minecraft:basic_flame_particle ~2.5 ~2 ~0.5
particle minecraft:basic_flame_particle ~2.5 ~2 ~1.0
particle minecraft:basic_flame_particle ~2.5 ~2 ~1.5
