particle minecraft:basic_flame_particle ~-4.0 ~4 ~-2.0
particle minecraft:basic_flame_particle ~-4.0 ~4 ~-1.5
particle minecraft:basic_flame_particle ~-4.0 ~4 ~-1.0
particle minecraft:basic_flame_particle ~-4.0 ~4 ~-0.5
particle minecraft:basic_flame_particle ~-4.0 ~4 ~0.0
particle minecraft:basic_flame_particle ~-4.0 ~4 ~0.5
particle minecraft:basic_flame_particle ~-4.0 ~4 ~1.0
particle minecraft:basic_flame_particle ~-4.0 ~4 ~1.5
particle minecraft:basic_flame_particle ~-4.0 ~4 ~2.0
particle minecraft:basic_flame_particle ~-3.5 ~4 ~-2.5
particle minecraft:basic_flame_particle ~-3.5 ~4 ~-2.0
particle minecraft:basic_flame_particle ~-3.5 ~4 ~2.0
particle minecraft:basic_flame_particle ~-3.5 ~4 ~2.5
particle minecraft:basic_flame_particle ~-3.0 ~4 ~-3.0
particle minecraft:basic_flame_particle ~-3.0 ~4 ~3.0
particle minecraft:basic_flame_particle ~-2.5 ~4 ~-3.5
particle minecraft:basic_flame_particle ~-2.5 ~4 ~3.5
particle minecraft:basic_flame_particle ~-2.0 ~4 ~-4.0
particle minecraft:basic_flame_particle ~-2.0 ~4 ~-3.5
particle minecraft:basic_flame_particle ~-2.0 ~4 ~3.5
particle minecraft:basic_flame_particle ~-2.0 ~4 ~4.0
particle minecraft:basic_flame_particle ~-1.5 ~4 ~-4.0
particle minecraft:basic_flame_particle ~-1.5 ~4 ~4.0
particle minecraft:basic_flame_particle ~-1.0 ~4 ~-4.0
particle minecraft:basic_flame_particle ~-1.0 ~4 ~4.0
particle minecraft:basic_flame_particle ~-0.5 ~4 ~-4.0
particle minecraft:basic_flame_particle ~-0.5 ~4 ~4.0
particle minecraft:basic_flame_particle ~0.0 ~4 ~-4.0
particle minecraft:basic_flame_particle ~0.0 ~4 ~4.0
particle minecraft:basic_flame_particle ~0.5 ~4 ~-4.0
particle minecraft:basic_flame_particle ~0.5 ~4 ~4.0
particle minecraft:basic_flame_particle ~1.0 ~4 ~-4.0
particle minecraft:basic_flame_particle ~1.0 ~4 ~4.0
particle minecraft:basic_flame_particle ~1.5 ~4 ~-4.0
particle minecraft:basic_flame_particle ~1.5 ~4 ~4.0
particle minecraft:basic_flame_particle ~2.0 ~4 ~-4.0
particle minecraft:basic_flame_particle ~2.0 ~4 ~-3.5
particle minecraft:basic_flame_particle ~2.0 ~4 ~3.5
particle minecraft:basic_flame_particle ~2.0 ~4 ~4.0
particle minecraft:basic_flame_particle ~2.5 ~4 ~-3.5
particle minecraft:basic_flame_particle ~2.5 ~4 ~3.5
particle minecraft:basic_flame_particle ~3.0 ~4 ~-3.0
particle minecraft:basic_flame_particle ~3.0 ~4 ~3.0
particle minecraft:basic_flame_particle ~3.5 ~4 ~-2.5
particle minecraft:basic_flame_particle ~3.5 ~4 ~-2.0
particle minecraft:basic_flame_particle ~3.5 ~4 ~2.0
particle minecraft:basic_flame_particle ~3.5 ~4 ~2.5
particle minecraft:basic_flame_particle ~4.0 ~4 ~-2.0
particle minecraft:basic_flame_particle ~4.0 ~4 ~-1.5
particle minecraft:basic_flame_particle ~4.0 ~4 ~-1.0
particle minecraft:basic_flame_particle ~4.0 ~4 ~-0.5
particle minecraft:basic_flame_particle ~4.0 ~4 ~0.0
particle minecraft:basic_flame_particle ~4.0 ~4 ~0.5
particle minecraft:basic_flame_particle ~4.0 ~4 ~1.0
particle minecraft:basic_flame_particle ~4.0 ~4 ~1.5
particle minecraft:basic_flame_particle ~4.0 ~4 ~2.0
