particle minecraft:basic_flame_particle ~-2.5 ~6 ~-1.5
particle minecraft:basic_flame_particle ~-2.5 ~6 ~-1.0
particle minecraft:basic_flame_particle ~-2.5 ~6 ~-0.5
particle minecraft:basic_flame_particle ~-2.5 ~6 ~0.0
particle minecraft:basic_flame_particle ~-2.5 ~6 ~0.5
particle minecraft:basic_flame_particle ~-2.5 ~6 ~1.0
particle minecraft:basic_flame_particle ~-2.5 ~6 ~1.5
particle minecraft:basic_flame_particle ~-2.0 ~6 ~-2.0
particle minecraft:basic_flame_particle ~-2.0 ~6 ~-1.5
particle minecraft:basic_flame_particle ~-2.0 ~6 ~1.5
particle minecraft:basic_flame_particle ~-2.0 ~6 ~2.0
particle minecraft:basic_flame_particle ~-1.5 ~6 ~-2.5
particle minecraft:basic_flame_particle ~-1.5 ~6 ~-2.0
particle minecraft:basic_flame_particle ~-1.5 ~6 ~2.0
particle minecraft:basic_flame_particle ~-1.5 ~6 ~2.5
particle minecraft:basic_flame_particle ~-1.0 ~6 ~-2.5
particle minecraft:basic_flame_particle ~-1.0 ~6 ~2.5
particle minecraft:basic_flame_particle ~-0.5 ~6 ~-2.5
particle minecraft:basic_flame_particle ~-0.5 ~6 ~2.5
particle minecraft:basic_flame_particle ~0.0 ~6 ~-2.5
particle minecraft:basic_flame_particle ~0.0 ~6 ~2.5
particle minecraft:basic_flame_particle ~0.5 ~6 ~-2.5
particle minecraft:basic_flame_particle ~0.5 ~6 ~2.5
particle minecraft:basic_flame_particle ~1.0 ~6 ~-2.5
particle minecraft:basic_flame_particle ~1.0 ~6 ~2.5
particle minecraft:basic_flame_particle ~1.5 ~6 ~-2.5
particle minecraft:basic_flame_particle ~1.5 ~6 ~-2.0
particle minecraft:basic_flame_particle ~1.5 ~6 ~2.0
particle minecraft:basic_flame_particle ~1.5 ~6 ~2.5
particle minecraft:basic_flame_particle ~2.0 ~6 ~-2.0
particle minecraft:basic_flame_particle ~2.0 ~6 ~-1.5
particle minecraft:basic_flame_particle ~2.0 ~6 ~1.5
particle minecraft:basic_flame_particle ~2.0 ~6 ~2.0
particle minecraft:basic_flame_particle ~2.5 ~6 ~-1.5
particle minecraft:basic_flame_particle ~2.5 ~6 ~-1.0
particle minecraft:basic_flame_particle ~2.5 ~6 ~-0.5
particle minecraft:basic_flame_particle ~2.5 ~6 ~0.0
particle minecraft:basic_flame_particle ~2.5 ~6 ~0.5
particle minecraft:basic_flame_particle ~2.5 ~6 ~1.0
particle minecraft:basic_flame_particle ~2.5 ~6 ~1.5
