particle minecraft:basic_flame_particle ~-1.0 ~8 ~-1.0
particle minecraft:basic_flame_particle ~-1.0 ~8 ~-0.5
particle minecraft:basic_flame_particle ~-1.0 ~8 ~0.0
particle minecraft:basic_flame_particle ~-1.0 ~8 ~0.5
particle minecraft:basic_flame_particle ~-1.0 ~8 ~1.0
particle minecraft:basic_flame_particle ~-0.5 ~8 ~-1.0
particle minecraft:basic_flame_particle ~-0.5 ~8 ~1.0
particle minecraft:basic_flame_particle ~0.0 ~8 ~-1.0
particle minecraft:basic_flame_particle ~0.0 ~8 ~1.0
particle minecraft:basic_flame_particle ~0.5 ~8 ~-1.0
particle minecraft:basic_flame_particle ~0.5 ~8 ~1.0
particle minecraft:basic_flame_particle ~1.0 ~8 ~-1.0
particle minecraft:basic_flame_particle ~1.0 ~8 ~-0.5
particle minecraft:basic_flame_particle ~1.0 ~8 ~0.0
particle minecraft:basic_flame_particle ~1.0 ~8 ~0.5
particle minecraft:basic_flame_particle ~1.0 ~8 ~1.0
