particle minecraft:balloon_gas_particle ~ ~2.0 ~
particle minecraft:balloon_gas_particle ~ ~2.5 ~
particle minecraft:balloon_gas_particle ~ ~3.0 ~
particle minecraft:balloon_gas_particle ~ ~3.5 ~
particle minecraft:balloon_gas_particle ~ ~4.0 ~
particle minecraft:balloon_gas_particle ~ ~4.5 ~
particle minecraft:balloon_gas_particle ~ ~5.0 ~
particle minecraft:balloon_gas_particle ~ ~5.5 ~
particle minecraft:balloon_gas_particle ~ ~6.0 ~
particle minecraft:balloon_gas_particle ~ ~6.5 ~
particle minecraft:balloon_gas_particle ~ ~7.0 ~
particle minecraft:balloon_gas_particle ~ ~7.5 ~
particle minecraft:balloon_gas_particle ~ ~8.0 ~
particle minecraft:balloon_gas_particle ~ ~8.5 ~
particle minecraft:balloon_gas_particle ~ ~9.0 ~
particle minecraft:balloon_gas_particle ~ ~9.5 ~
particle minecraft:balloon_gas_particle ~ ~10.0 ~
particle minecraft:balloon_gas_particle ~ ~10.5 ~
particle minecraft:balloon_gas_particle ~ ~11.0 ~
particle minecraft:balloon_gas_particle ~ ~11.5 ~
