particle minecraft:balloon_gas_particle ~-2.0 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~-2.0 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~-2.0 ~1 ~0.0
particle minecraft:balloon_gas_particle ~-2.0 ~1 ~0.5
particle minecraft:balloon_gas_particle ~-2.0 ~1 ~1.0
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~0.0
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~0.5
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~1.0
particle minecraft:balloon_gas_particle ~-1.5 ~1 ~1.5
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~-2.0
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~0.0
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~0.5
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~1.0
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~1.5
particle minecraft:balloon_gas_particle ~-1.0 ~1 ~2.0
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~-2.0
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~1.0
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~1.5
particle minecraft:balloon_gas_particle ~-0.5 ~1 ~2.0
particle minecraft:balloon_gas_particle ~0.0 ~1 ~-2.0
particle minecraft:balloon_gas_particle ~0.0 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~0.0 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~0.0 ~1 ~1.0
particle minecraft:balloon_gas_particle ~0.0 ~1 ~1.5
particle minecraft:balloon_gas_particle ~0.0 ~1 ~2.0
particle minecraft:balloon_gas_particle ~0.5 ~1 ~-2.0
particle minecraft:balloon_gas_particle ~0.5 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~0.5 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~0.5 ~1 ~1.0
particle minecraft:balloon_gas_particle ~0.5 ~1 ~1.5
particle minecraft:balloon_gas_particle ~0.5 ~1 ~2.0
particle minecraft:balloon_gas_particle ~1.0 ~1 ~-2.0
particle minecraft:balloon_gas_particle ~1.0 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~1.0 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~1.0 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~1.0 ~1 ~0.0
particle minecraft:balloon_gas_particle ~1.0 ~1 ~0.5
particle minecraft:balloon_gas_particle ~1.0 ~1 ~1.0
particle minecraft:balloon_gas_particle ~1.0 ~1 ~1.5
particle minecraft:balloon_gas_particle ~1.0 ~1 ~2.0
particle minecraft:balloon_gas_particle ~1.5 ~1 ~-1.5
particle minecraft:balloon_gas_particle ~1.5 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~1.5 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~1.5 ~1 ~0.0
particle minecraft:balloon_gas_particle ~1.5 ~1 ~0.5
particle minecraft:balloon_gas_particle ~1.5 ~1 ~1.0
particle minecraft:balloon_gas_particle ~1.5 ~1 ~1.5
particle minecraft:balloon_gas_particle ~2.0 ~1 ~-1.0
particle minecraft:balloon_gas_particle ~2.0 ~1 ~-0.5
particle minecraft:balloon_gas_particle ~2.0 ~1 ~0.0
particle minecraft:balloon_gas_particle ~2.0 ~1 ~0.5
particle minecraft:balloon_gas_particle ~2.0 ~1 ~1.0
